### ISSUE TITLE
missing windows

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/dynosaur#3]
![image](https://user-images.githubusercontent.com/2915573/31061291-ab391a9c-a6ed-11e7-9362-18de87322f70.png)

**Comment by mostaphaRoudsari** [comment]
made some progress!
![image](https://user-images.githubusercontent.com/2915573/31062093-01895846-a6f6-11e7-9724-ee564fd5f9de.png)

**Comment by mostaphaRoudsari** [comment]
Here is the last one! with a little bit extra info! 🤔 

![image](https://user-images.githubusercontent.com/2915573/31062294-8e9ae0e6-a6f7-11e7-92b4-686a7ae91b4c.png)

**Comment by mostaphaRoudsari** [comment]
Getting there:
![image](https://user-images.githubusercontent.com/2915573/31090444-9d02be14-a775-11e7-865c-132afeb00ac7.png)

**Comment by mostaphaRoudsari** [comment]
![image](https://user-images.githubusercontent.com/2915573/31093807-e688b204-a780-11e7-98ec-aa5c440138bf.png)

**Comment by mdengusiak** [comment]
This looks great... you really covered not only windows but also Curtain wall which is separate category .. great
